default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres 
  password: malik123

development:
  <<: *default
  database: workout_tracker_development

test:
  <<: *default
  database: workout_tracker_test

production:
  primary: &primary
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cable:
    <<: *primary
  cache:
    <<: *primary
  queue:
    <<: *primary